name: /Users/donglaima/tensorflow-test/env
channels:
  - apple
  - defaults
  - conda-forge
dependencies:
  - adwaita-icon-theme=40.1.1=hca03da5_1
  - appnope=0.1.2=py38hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h1a28f6b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atk-1.0=2.36.0=h7fe96df_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.4=py38heec5a64_0
  - brotli=1.0.7=hc377ac9_0
  - c-ares=1.18.1=h1a28f6b_0
  - ca-certificates=2022.4.26=hca03da5_0
  - cairo=1.16.0=h0ab239c_1
  - cffi=1.15.0=py38h22df2f2_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=h8280c03_0
  - debugpy=1.5.1=py38hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38hca03da5_0
  - epoxy=1.5.4=h1a28f6b_2
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=hc377ac9_0
  - fontconfig=2.13.1=h1f4a5ec_0
  - freetype=2.11.0=h1192e45_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.6=h74ef11a_4
  - gettext=0.21.0=h826f4ad_0
  - giflib=5.2.1=h1a28f6b_0
  - glib=2.69.1=h98b2900_1
  - gobject-introspection=1.68.0=py38h3459c9f_3
  - graphite2=1.3.14=h0e5e14a_0
  - grpcio=1.42.0=py38h95c9599_0
  - gtk3=3.24.21=h321fa23_1
  - h5py=3.6.0=py38h7fe8675_0
  - harfbuzz=2.8.1=hffeda63_0
  - hdf5=1.12.1=h5aa262f_1
  - hicolor-icon-theme=0.17=hca03da5_2
  - icu=68.1=hc377ac9_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - ipykernel=6.9.1=py38hca03da5_0
  - ipython=8.3.0=py38hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py38hca03da5_1
  - jpeg=9e=h1a28f6b_0
  - jsonschema=4.4.0=py38hca03da5_0
  - jupyter=1.0.0=py38hca03da5_7
  - jupyter_client=7.2.2=py38hca03da5_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - krb5=1.19.2=h3b8d789_0
  - lcms2=2.12=hba8e193_0
  - libblas=3.9.0=13_osxarm64_openblas
  - libcblas=3.9.0=13_osxarm64_openblas
  - libcurl=7.82.0=hc6d1d07_0
  - libcxx=12.0.0=hf6beb65_1
  - libedit=3.1.20210910=h1a28f6b_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=hf27765b_0
  - libffi=3.4.2=hc377ac9_2
  - libgfortran=5.0.0=11_1_0_h6a59814_26
  - libgfortran5=11.1.0=h6a59814_26
  - libiconv=1.16=h1a28f6b_2
  - liblapack=3.9.0=13_osxarm64_openblas
  - libllvm11=11.1.0=h12f7ac0_4
  - libnghttp2=1.46.0=h95c9599_0
  - libopenblas=0.3.18=hea475bc_0
  - libpng=1.6.37=hb8d0fd4_0
  - libpq=12.9=h65cfe13_1
  - librsvg=2.50.7=h90a7944_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.10.0=hf27765b_0
  - libtiff=4.2.0=h11e2f9f_0
  - libwebp=1.2.2=h68602c7_0
  - libwebp-base=1.2.2=h1a28f6b_0
  - libxml2=2.9.12=h8c5e841_1
  - libxslt=1.1.34=h9833966_0
  - llvm-openmp=12.0.0=haf9daa7_1
  - llvmlite=0.38.0=py38h98b2900_0
  - lz4-c=1.9.3=hc377ac9_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h1a28f6b_1000
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py38hca03da5_0
  - nbconvert=6.4.4=py38hca03da5_0
  - nbformat=5.3.0=py38hca03da5_0
  - ncurses=6.3=h1a28f6b_2
  - nest-asyncio=1.5.5=py38hca03da5_0
  - ninja=1.10.2=hca03da5_5
  - ninja-base=1.10.2=h525c30c_5
  - notebook=6.4.11=py38hca03da5_0
  - nspr=4.33=hc377ac9_0
  - nss=3.74=h142855e_0
  - numba=0.55.1=py38h9197a36_0
  - openssl=1.1.1o=h1a28f6b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.48.7=h79d33a7_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hc377ac9_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py38hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyqt=5.15.2=py38he8f2410_0
  - pyrsistent=0.18.0=py38h1a28f6b_0
  - python=3.8.13=hbdb9e5c_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pyzmq=22.3.0=py38hc377ac9_2
  - qt=5.15.2=h4e944ae_2
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.1.2=h1a28f6b_1
  - scikit-learn=1.0.2=py38h9197a36_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py38hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.3=h1058600_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.5.0=h525c30c_0
  - tensorflow-deps=2.8.0=0
  - terminado=0.13.1=py38hca03da5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=hb8d0fd4_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38hca03da5_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38hca03da5_0
  - xz=5.2.5=h1a28f6b_1
  - zeromq=4.3.4=hc377ac9_0
  - zlib=1.2.12=h5a0b063_2
  - zstd=1.4.9=h8574219_1
  - pip:
    - absl-py==1.0.0
    - alembic==1.8.1
    - astropy==5.2.1
    - astunparse==1.6.3
    - autopage==0.5.1
    - blosc2==2.0.0
    - bokeh==2.4.3
    - brewer2mpl==1.4.1
    - cachetools==5.1.0
    - cdasws==1.7.42
    - cdflib==0.4.9
    - certifi==2022.12.7
    - cftime==1.6.2
    - charset-normalizer==3.1.0
    - cliff==4.1.0
    - cloudpickle==2.0.0
    - cmaes==0.9.0
    - cmd2==2.4.2
    - colorlog==6.7.0
    - contourpy==1.0.7
    - cython==0.29.33
    - dill==0.3.4
    - flatbuffers==2.0
    - fonttools==4.39.2
    - future==0.18.2
    - gast==0.5.3
    - geopack==1.0.10
    - ggplot==0.11.5
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.56.1
    - hapiclient==0.2.5
    - html5lib==1.1
    - idna==3.4
    - imageio==2.21.2
    - importlib-metadata==4.11.3
    - importlib-resources==5.12.0
    - isodate==0.6.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.1
    - mako==1.2.4
    - markdown==3.3.7
    - markupsafe==2.1.2
    - mat73==0.59
    - matplotlib==3.7.1
    - mechanize==0.4.8
    - mizani==0.7.4
    - mlflow==1.27.0
    - mpmath==1.2.1
    - msgpack==1.0.5
    - netcdf4==1.6.3
    - networkx==2.8.6
    - numexpr==2.8.4
    - numpy==1.21.6
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - optuna==3.0.0b1
    - packaging==23.0
    - palettable==3.3.0
    - pandas==1.5.3
    - patsy==0.5.2
    - pbr==5.11.0
    - pillow==9.4.0
    - plotly==5.13.0
    - plotnine==0.9.0
    - prettytable==3.5.0
    - promise==2.3
    - protobuf==3.20.1
    - py-cpuinfo==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.10.0
    - pycwt==0.4.0b0
    - pyerfa==2.0.0.3
    - pyparsing==3.0.9
    - pyperclip==1.8.2
    - pyqt5-sip==4.19.25
    - pyqtchart==5.15.2
    - pyspedas==1.4.25
    - pytplot-mpl-temp==2.1.25
    - pytz==2022.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-image==0.19.3
    - scipy==1.10.1
    - scs==3.2.0
    - seaborn==0.12.0
    - shap==0.40.0
    - shapely==1.8.2
    - sklearn==0.0
    - slicer==0.0.7
    - sqlalchemy==1.4.44
    - statsmodels==0.13.2
    - stevedore==4.1.1
    - sympy==1.10.1
    - tables==3.8.0
    - tenacity==8.2.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-datasets==4.5.2
    - tensorflow-macos==2.8.0
    - tensorflow-metadata==1.8.0
    - tensorflow-metal==0.4.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - tifffile==2022.8.12
    - tornado==6.2
    - tqdm==4.65.0
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - viresclient==0.11.1
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - xarray==2023.1.0
    - xgboost==1.6.1
    - xyzservices==2022.4.0
    - zipp==3.15.0
prefix: /Users/donglaima/tensorflow-test/env
